version: '2'
services:
        backend-service:
                build: ./backend
                ports:
                - "8123:8123"
                links:
                - "mysql"
                depends_on:
                - db
                environment:
                - DATABASE_HOST=db
                tty: true
        db:
                #image: mysql:5.7
                ports:
                - "3306:3306"
                restart: always
                build: ./database
                volumes:
                - /home/code/data/golang-mysql/:/var/lib/mysql/
                environment:
                - MYSQL_ROOT_PASSWORD=123456




